version: '3'
services:
  postgres:
    container_name: amigos-postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: amigos-zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: amigos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.12.1
    container_name: amigos-elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
      #      It basically runs it with SSL disabled, allowing you to create HTTP connections with it
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    networks:
      - elastic

  logstash:
    image: logstash:8.12.1
    container_name: amigos-logstash
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "9600:9600"
      - "5000:5000/tcp"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  kibana:
    image: kibana:8.12.1
    container_name: amigos-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge

volumes:
  postgres:
  pgadmin: